#include "array.cc"
Array_Copy_Compare_Sort_Default(int8)
//Array_Copy_Compare_Sort_Default(uint8)
//Array_Copy_Compare_Sort_Default(int16)
//Array_Copy_Compare_Sort_Default(uint16)
Array_Copy_Compare_Sort_Default(int32)
Array_Copy_Compare_Sort_Default(uint32)
//Array_Copy_Compare_Sort_Default(int64)
//Array_Copy_Compare_Sort_Default(uint64)
//Array_Copy_Compare_Sort_Default(float)
