#include "array.cc"
PlainArray(int8)
//PlainArray(uint8)
//PlainArray(int16)
//PlainArray(uint16)
//PlainArray(int32)
//PlainArray(uint32)
//PlainArray(int64)
//PlainArray(uint64)
//PlainArray(float)
