#include "array.cc"
PlainArray(byte)
PlainArray(ubyte)
PlainArray(int16)
PlainArray(uint16)
PlainArray(int)
PlainArray(uint)
PlainArray(long)
PlainArray(unsigned long)
PlainArray(int64)
PlainArray(uint64)
PlainArray(float)
