var files =
[
    [ "array.h", "array_8h.html", "array_8h" ],
    [ "build.cc", "build_8cc.html", "build_8cc" ],
    [ "CG.cc", "_c_g_8cc.html", "_c_g_8cc" ],
    [ "CG.h", "_c_g_8h.html", [
      [ "CG", "struct_c_g.html", "struct_c_g" ]
    ] ],
    [ "compute.cc", "compute_8cc.html", "compute_8cc" ],
    [ "core.h", "core_8h.html", "core_8h" ],
    [ "data.cc", "data_8cc.html", null ],
    [ "data.h", "data_8h.html", "data_8h" ],
    [ "deflate.cc", "deflate_8cc.html", "deflate_8cc" ],
    [ "deflate.h", "deflate_8h.html", "deflate_8h" ],
    [ "file.cc", "file_8cc.html", "file_8cc" ],
    [ "file.h", "file_8h.html", "file_8h" ],
    [ "font.cc", "font_8cc.html", null ],
    [ "font.h", "font_8h.html", [
      [ "Glyph", "struct_glyph.html", "struct_glyph" ],
      [ "Font", "struct_font.html", "struct_font" ]
    ] ],
    [ "function.h", "function_8h.html", "function_8h" ],
    [ "graph.cc", "graph_8cc.html", "graph_8cc" ],
    [ "graphics.cc", "graphics_8cc.html", "graphics_8cc" ],
    [ "graphics.h", "graphics_8h.html", "graphics_8h" ],
    [ "image.cc", "image_8cc.html", "image_8cc" ],
    [ "image.h", "image_8h.html", "image_8h" ],
    [ "layout.cc", "layout_8cc.html", null ],
    [ "layout.h", "layout_8h.html", [
      [ "Layout", "struct_layout.html", "struct_layout" ],
      [ "WidgetReferences", "struct_widget_references.html", "struct_widget_references" ],
      [ "WidgetValues", "struct_widget_values.html", "struct_widget_values" ],
      [ "Linear", "struct_linear.html", "struct_linear" ],
      [ "Horizontal", "struct_horizontal.html", "struct_horizontal" ],
      [ "Vertical", "struct_vertical.html", "struct_vertical" ],
      [ "HBox", "struct_h_box.html", "struct_h_box" ],
      [ "VBox", "struct_v_box.html", "struct_v_box" ],
      [ "HList", "struct_h_list.html", "struct_h_list" ],
      [ "VList", "struct_v_list.html", "struct_v_list" ],
      [ "GridLayout", "struct_grid_layout.html", "struct_grid_layout" ],
      [ "WidgetGrid", "struct_widget_grid.html", "struct_widget_grid" ],
      [ "UniformGrid", "struct_uniform_grid.html", "struct_uniform_grid" ],
      [ "Value", "struct_value.html", "struct_value" ]
    ] ],
    [ "map.h", "map_8h.html", "map_8h" ],
    [ "math.h", "math_8h.html", "math_8h" ],
    [ "matrix.h", "matrix_8h.html", "matrix_8h" ],
    [ "memory.cc", "memory_8cc.html", null ],
    [ "memory.h", "memory_8h.html", "memory_8h" ],
    [ "MLTR.cc", "_m_l_t_r_8cc.html", null ],
    [ "MLTR.h", "_m_l_t_r_8h.html", [
      [ "MLTR", "struct_m_l_t_r.html", "struct_m_l_t_r" ]
    ] ],
    [ "opencl.cc", "opencl_8cc.html", "opencl_8cc" ],
    [ "opencl.h", "opencl_8h.html", "opencl_8h" ],
    [ "operators.cc", "operators_8cc.html", "operators_8cc" ],
    [ "operators.h", "operators_8h.html", "operators_8h" ],
    [ "plot.cc", "plot_8cc.html", "plot_8cc" ],
    [ "plot.h", "plot_8h.html", "plot_8h" ],
    [ "PMLTR.cc", "_p_m_l_t_r_8cc.html", null ],
    [ "PMLTR.h", "_p_m_l_t_r_8h.html", [
      [ "PMLTR", "struct_p_m_l_t_r.html", "struct_p_m_l_t_r" ]
    ] ],
    [ "png.cc", "png_8cc.html", "png_8cc" ],
    [ "png.h", "png_8h.html", "png_8h" ],
    [ "profile.cc", "profile_8cc.html", "profile_8cc" ],
    [ "project.cc", "project_8cc.html", "project_8cc" ],
    [ "project.h", "project_8h.html", "project_8h" ],
    [ "projection.h", "projection_8h.html", "projection_8h" ],
    [ "random.h", "random_8h.html", "random_8h" ],
    [ "reconstruction.h", "reconstruction_8h.html", [
      [ "Reconstruction", "struct_reconstruction.html", "struct_reconstruction" ],
      [ "SubsetReconstruction", "struct_subset_reconstruction.html", "struct_subset_reconstruction" ],
      [ "Subset", "struct_subset_reconstruction_1_1_subset.html", "struct_subset_reconstruction_1_1_subset" ]
    ] ],
    [ "review.cc", "review_8cc.html", "review_8cc" ],
    [ "SART.cc", "_s_a_r_t_8cc.html", null ],
    [ "SART.h", "_s_a_r_t_8h.html", [
      [ "SART", "struct_s_a_r_t.html", "struct_s_a_r_t" ]
    ] ],
    [ "slice.cc", "slice_8cc.html", "slice_8cc" ],
    [ "SNR.cc", "_s_n_r_8cc.html", "_s_n_r_8cc" ],
    [ "string.cc", "string_8cc.html", "string_8cc" ],
    [ "string.h", "string_8h.html", "string_8h" ],
    [ "synthetic.cc", "synthetic_8cc.html", "synthetic_8cc" ],
    [ "synthetic.h", "synthetic_8h.html", "synthetic_8h" ],
    [ "test.cc", "test_8cc.html", "test_8cc" ],
    [ "text.cc", "text_8cc.html", "text_8cc" ],
    [ "text.h", "text_8h.html", "text_8h" ],
    [ "thread.cc", "thread_8cc.html", "thread_8cc" ],
    [ "thread.h", "thread_8h.html", "thread_8h" ],
    [ "time.cc", "time_8cc.html", "time_8cc" ],
    [ "time.h", "time_8h.html", "time_8h" ],
    [ "trace.cc", "trace_8cc.html", "trace_8cc" ],
    [ "trace.h", "trace_8h.html", "trace_8h" ],
    [ "utf8.cc", "utf8_8cc.html", "utf8_8cc" ],
    [ "utf8.h", "utf8_8h.html", "utf8_8h" ],
    [ "variant.h", "variant_8h.html", "variant_8h" ],
    [ "vector.h", "vector_8h.html", "vector_8h" ],
    [ "view.cc", "view_8cc.html", null ],
    [ "view.h", "view_8h.html", [
      [ "SliceView", "struct_slice_view.html", "struct_slice_view" ],
      [ "VolumeView", "struct_volume_view.html", "struct_volume_view" ]
    ] ],
    [ "volume.h", "volume_8h.html", "volume_8h" ],
    [ "widget.cc", "widget_8cc.html", "widget_8cc" ],
    [ "widget.h", "widget_8h.html", "widget_8h" ],
    [ "window.cc", "window_8cc.html", "window_8cc" ],
    [ "window.h", "window_8h.html", "window_8h" ],
    [ "x.h", "x_8h.html", "x_8h" ]
];