trunk contraction ratio : r1=0.9
branches contraction ratio : r2=0.6
trunk branching angle : a0=45
lateral branching angle : a2=45
trunk divergence angle : d=137.5
width decrease rate 1/sqrt(2) : wr=0.707

main axis : A(l,w) → !(w)F(l)[&(a0)B(l*r2,w*wr)]/(d)A(l*r1,w*wr )
lateral branch : B(l,w) → !(w)F(l)[-(a2)$C(l*r2,w*wr)]C(l*r1,w*wr)
lateral branch (alternate) : C(l,w) → !(w)F(l)[+(a2)$B(l*r2,w*wr)]B(l*r1,w*wr)

A(1,10)
