#!/bin/sh
PV=$(basename ${1%.tar.*})
BUILD=/dev/shm #BUILD=/ptmp/build/
test -e $BUILD/$PV* || unpack $1 || exit
test -e /dev/shm/rock && echo "Removing /dev/shm/rock" && rm -rf /dev/shm/rock
echo "Building $PV"
cd $BUILD/$PV*
export PATH=/ptmp/bin:/usr/bin:/bin
export LD_LIBRARY_PATH=/ptmp/lib:/usr/lib/lib
export PKG_CONFIG_PATH=/ptmp/lib/pkgconfig
export CMAKE_ROOT=/ptmp/share/cmake-2.8
export CPPFLAGS=-I/ptmp/include 
export LDFLAGS=-L/ptmp/lib
export QTDIR=/ptmp
export QMAKESPEC=/ptmp/mkspecs/linux-g++
test -e CMakeLists.txt && mkdir -p ../build_$PV && cd ../build_$PV && echo $PWD && cmake ../$PV* -DCMAKE_INSTALL_PREFIX:PATH=/ptmp ${*:2} && make -j8 && make install && exit 0
test -e configure && ./configure --prefix /ptmp ${*:2} && make -j8 && make install && exit 0
test -e *.pro && qmake -r && make -j8 && make install INSTALL_ROOT=/ptmp && exit 0
test -e Makefile && make -j8 && make install PREFIX=/ptmp && exit 0
test -e makefile && make -j8 && make install PREFIX=/ptmp && exit 0
echo "Failed to build $PV with options: ${*:2}" 
exit -1
