#!/bin/sh
FILE="$(list $1)"
test -z "$FILE" && echo "No match for $1" && exit -1
[[ $FILE == *$'\n'* ]] && echo -e "Multiple matches:\n$FILE" && exit -1
#TODO: find file name (i.e with extension) from name-version
#TODO: find latest package version from package name
PV=$(basename ${1%.tar.*})
echo "Fetching '$FILE'"
cd /ptmp/distfiles
wget -N http://distfiles.gentoo.org/distfiles/$FILE || exit
